---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/abitcons/abit.ai/
    - /bin/mkdir -p $DEPLOYPATH/wp-content/themes/astra
    - /bin/cp -f wp-content/themes/astra/functions.php $DEPLOYPATH/wp-content/themes/astra/functions.php
    - /bin/cp -f web.config $DEPLOYPATH/web.config
